### PR TITLE
no viewbox makes this impossible to scale to fit parent

### PR DESCRIPTION
**Pull request by andreigec**
before:
image

after
image

### CODE REVIEW

**Comment by Josh-Cena** [comment]
LGTM, would it make sense to have both width/height and viewbox?

**Comment by andreigec** [comment]
@Josh-Cena  I'm not a master of svg, but when i set viewbox and leave width/height, it looks (just as) broken as the before picture

**Comment by Josh-Cena** [comment]
Too awful that we use GitHub pages for the website so there's no way for me to preview the effect before merging. I'm going to merge this, and if it doesn't work out (e.g. doesn't allow customizing sizes), I'll let you know so we can figure out how to properly address it. Thanks!

**Comment by Josh-Cena** [comment]
Too awful that we use GitHub pages for the website so there's no way for me to preview the effect before merging. I'm going to merge this, and if it doesn't work out (e.g. doesn't allow customizing sizes), I'll let you know so we can figure out how to properly address it. Thanks!

**Comment by Josh-Cena** [comment]
Hey @andreigec FYI your change didn't work out https://yanivam.github.io/react-svg-worldmap/examples/sizing

Sorry I was too lazy to test this locally first. Would you mind testing this yourself and see how to better fix this? You can install this locally and run `yarn start` in the website folder to preview the effect.

**Comment by andreigec** [comment]
@Josh-Cena  not sure when you say it doesnt work out - the resizing here is what i expect?

**Comment by Josh-Cena** [comment]
Previously, every map should be a different size determined by the hardcoded width; now, if you change the tabs, all the maps have largest size that fits the container.

**Comment by andreigec** [comment]
Ok the issue is actually that the "responsive" sizing mode is using the window width/height:
https://github.com/yanivam/react-svg-worldmap/blob/main/lib/src/utils.ts#L29

This wont work if the svg occupies a div that is not the full width of the screen - like with my example where it is roughly half the screen.

**Comment by Josh-Cena** [comment]
Ah, so we should use the bounding container's width instead. Would you send another PR to revert this change and see how we could retrieve the parent container's width? In the worst case we can just apply viewbox to responsive maps.

**Pull request merged**
