### PR TITLE
Exposed geoData

### PR DESCRIPTION
**Pull request by MelColmant**
Hi,

I really enjoy using your project. It's easy to set up and use.

I have just exposed the 'geoData' to give more flexibility to translate the country names in different languages.

Let me know what you think.

Mel

### CODE REVIEW

**Comment by yanivam** [comment]
This is so sweet! Sorry I didn't see this until now, have been really busy with school recently and haven't been able to get to working on this. Will work on getting this approved and merged soon! I really appreciate the help and I am so glad that you are enjoying my project!

**Comment by yanivam** [comment]
I think I may have an idea to incorporate this feature using a callback function. Will let you know when I figure that out/get it working.

**Comment by MelColmant** [comment]
Hey,

Thanks for getting back to me.

That's great. Just let me know.

Best,

Mel

________________________________
De : Yams <notifications@github.com>
Envoyé : vendredi 13 novembre 2020 19:23
À : yanivam/react-svg-worldmap <react-svg-worldmap@noreply.github.com>
Cc : MelColmant <m_colmant@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [yanivam/react-svg-worldmap] Exposed geoData (#57)


I think I may have an idea to incorporate this feature using a callback function. Will let you know when I figure that out/get it working.

**Comment by yanivam** [comment]
Hey Mel,

Thanks for your patience, I added a callback function called customTooltipTextFunction and pushed it to dev, going to work through some slight tweaks and changes but it is done for the most part and you can find an example of how to use it in the examples folder. I decided to not expose geoData, but instead allow for customization of the tooltip text using a callback function for simplicity and capability. Thank you so much for the suggestion, I think it will really help to make this project even better and I really appreciate your help. Feel free to check it out if you want before I publish it on the dev branch, but I will have those changes up soon.

Thanks,
Yaniv

**Comment by yanivam** [comment]
Changes now live on master and the version is updated, let me know what you think and if you need any help understanding how to use it.

**Comment by yanivam** [comment]
Hey Mel, I am going to close this pr since the changes were addressed in the last version. Let me know if you want more features I would love to hear an suggestion!

**Pull request closed without merging**
